//////////////////////////////////////////////////////////
// THIS FILE IS GENERATED BY CMAKE, PLEASE DO NOT CHANGE!
// Prefix: ${LIBRARY_PREFIX}
// Prefix (uppercase): ${LIBRARY_PREFIX_UPPER}
// Shader: ${SHADER_NAME}
// Shader (C): ${SHADER_NAME_C}
// Namespace: ${SHADER_NAMESPACE}
//////////////////////////////////////////////////////////
#include <${LIBRARY_PREFIX}/${SHADER_HEADER}.h>

namespace ${SHADER_NAMESPACE} {
constexpr static std::uint32_t const ${SHADER_NAME}_data[] = ${EMPLACEMENT_HINT};

${LIBRARY_PREFIX_UPPER}_EXPORT std::span<std::uint32_t const> ${SHADER_NAME}()
{
    return ${SHADER_NAME}_data;
}
}

#ifdef __cplusplus
extern "C" {
#endif
${LIBRARY_PREFIX_UPPER}_EXPORT uint32_t const* ${SHADER_NAME_C}()
{
    return ${SHADER_NAMESPACE}::${SHADER_NAME}().data();
}

${LIBRARY_PREFIX_UPPER}_EXPORT unsigned long long ${SHADER_NAME_C}_length()
{
    return ${SHADER_NAMESPACE}::${SHADER_NAME}().size();
}
#ifdef __cplusplus
}
#endif